spring.application.name=Color-craze

spring.data.mongodb.uri=mongodb+srv://emily:olecito3@color-craze.w6vlagc.mongodb.net/colorcraze?retryWrites=true&w=majority&appName=Color-Craze
spring.data.mongodb.database=colorcraze

# Puerto del servidor
server.port=8080


#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#por alguna razon me dejo todo menos la contraseña como valores validos

# Config CORS
app.cors.allowed-origins=http://localhost:3000,https://eci-bienestar.edu.co
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=Authorization,Content-Type,X-Requested-With
logging.level.org.mongodb.driver.cluster=WARN
logging.level.org.mongodb.driver.connection=WARN
logging.level.org.mongodb.driver.client=WARN
